### ISSUE TITLE
Android: System.DllNotFoundException: libllama

### ISSUE THREAD

**Issue by DifferentialityDevelopment** [drasticactions/llama.cpp.runtimes#1]
Hey there!

I was trying to get local llama running using .NET MAUI (used your other repo)
Got the app running except for the part where it's supposed to generate from the prompt I get this error
[monodroid-assembly] Shared library 'libllama' not loaded, p/invoke 'llama_context_default_params' may fail
[monodroid-assembly] Shared library 'libllama' not loaded, p/invoke 'llama_init_from_file' may fail
[monodroid-assembly] Shared library 'libllama' not loaded, p/invoke 'llama_apply_lora_from_file' may fail
[monodroid-assembly] Shared library 'libllama' not loaded, p/invoke 'llama_context_default_params' may fail
[0:] System.DllNotFoundException: libllama
   at LlamaCppLib.LlamaCpp.Load(String modelPath, String loraPath, String loraBaseModelPath) in C:\Users\t_mil\source\repos\Personal\Libraries\llama.cpp-dotnet\LlamaCppLib\LlamaCpp.cs:line 74
   at LLaMAMaui.ViewModels.MainViewModel.GenerateAsync() in C:\Personal\LLaMAMaui\src\LLaMAMaui\ViewModels\MainViewModel.cs:line 123
   at Drastic.Tools.AsyncCommand.ExecuteAsync() in C:\Users\t_mil\source\repos\Personal\Library\Drastic.Utilities\src\Drastic.Utilities\Tools\Commands\AsyncCommand.cs:line 78
   at Drastic.Tools.TaskUtilities.FireAndForgetSafeAsync(Task task, IErrorHandlerService handler) in C:\Users\t_mil\source\repos\Personal\Library\Drastic.Utilities\src\Drastic.Utilities\Tools\TaskUtilities.cs:line 25

I tried many things but can't seem to get it to work
I also tried adding this in the .csproj to get it to bundle the libraries with the native code.
<PropertyGroup Condition="'$(Configuration)|$(TargetFramework)|$(Platform)'=='Debug|net6.0-android|AnyCPU'">
		<EmbedAssembliesIntoApk>True</EmbedAssembliesIntoApk>
	</PropertyGroup>
[LLaMAMaui.csproj.txt](https://github.com/drasticactions/llama.cpp.runtimes/files/11574088/LLaMAMaui.csproj.txt)
[output.txt](https://github.com/drasticactions/llama.cpp.runtimes/files/11574123/output.txt)

**Comment by DifferentialityDevelopment** [comment]
I also tried adding JavaSystem.LoadLibrary("llama"); in LLaMAMaui\src\LLaMAMaui\Platforms\Android\MainApplication.cs
But that also didn't seem to work.
[mono-rt] [ERROR] FATAL UNHANDLED EXCEPTION: System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation.
[mono-rt]  ---> Java.Lang.UnsatisfiedLinkError: dlopen failed: library "libllama.so" not found
